site_name: "Neuroweaver Lab"
theme:
  name: "material"

nav:
  - Home: index.md
  - The Full Framework: advanced_guide.md
  - The Practice of Neuroweaver: implementation_guide.md
  - AI Integration Guide: Third_Mind-TECS.md
  - Get Involved: getting_involved.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.smartsymbols

plugins:
  - search

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/phillipclapham/neuroweaver
copyright: "This work is licensed under a <a href='https://creativecommons.org/licenses/by-nc-sa/4.0/'>CC BY-NC-SA 4.0 License</a>."
