site_name: "Neuroweaver Lab"
theme:
  name: "cinder"

nav:
  - Home: index.md
  - Daily Reference Guide: Daily_Reference_Guide.md
  - AI Integration Guide: AI_Integration_Guide.md
  - Sparking Your Dream Life:
      - Spark Your Dream Life: life/Spark_Your_Dream_Life.md
      - Daily Reference Guide: life/Daily_Reference_Guide.md
  - Advanced Studies:
      - Advanced Theory: advanced/Advanced_Theory.md
      - The Mad Scientist's Guide to Reality Engineering: advanced/mkdocs Mad_Scientists_Guide_to_Reality_Engineering.md
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.smartsymbols

plugins:
  - search
