site_name: "Neuroweaver Lab"
theme:
  name: "material"

nav:
  - Home: index.md
  - AI Integration Guide: Third_Mind-TECS.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.smartsymbols

plugins:
  - search
